name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    #env:
      #Solution_Name: WheatherPoc\WeatherPoc.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      #Test_Project_Path: WeatherPoc.Test\WeatherPoc.Test.csproj

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: WeatherPoc/WeatherPoc.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
